
spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile:
        - local
  data:
    mongodb:
      uri: mongodb+srv://ukpawanbhatt:prLhoI0zXHIzWnAF@cluster0.vezcxxn.mongodb.net/
---
spring:
  config:
    activate:
      on-profile:
        - dev
  data:
    mongodb:
      database: pawan-test
      uri: mongodb+srv://ukpawanbhatt:prLhoI0zXHIzWnAF@cluster0.vezcxxn.mongodb.net/
      auto-index-creation: true

server:
  port: 8081

